[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 88
select = ["E", "F", "W", "I001"]
target-version = "py311"

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
strict = true

